In [2]:
import numpy as np

In [3]:
a = np.arange(6) # 0부터 5까지 총 6개의 숫자출력
print(a)

[0 1 2 3 4 5]


In [14]:
a = np.arange(6) # 0부터 5까지 총 6개의 숫자출력
a = a.reshape(3,2) # 숫자을 2개씩 3줄로 출력
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [17]:
a = np.arange(8) # 0부터 7까지 총 8개의 숫자을 가지고 온다
print(a.reshape(2,2,2)) # 숫자을 2개씩 3줄로 출력

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [7]:
a = np.arange(6) # 0부터 5까지 총 6개의 숫자출력
a = a.reshape(3,2) # 숫자을 2개씩 3줄로 출력
print(a)

a = a + 10 # a변수에있는 리스트 숫자 전부에 10씩 더한 값출력
print(a)

[[0 1]
 [2 3]
 [4 5]]
[[10 11]
 [12 13]
 [14 15]]
