In [3]:
import numpy

In [23]:
data = numpy.arange(6) # 0부터 5까지 총 6개의 숫자출력
text = "{0} 차원, 데이터 리스트 {1}".format(data.ndim+1, data)
print(text)

2 차원, 데이터 리스트 [0 1 2 3 4 5]


In [26]:
data = numpy.arange(6) # 0부터 5까지 총 6개의 숫자출력
text = "{0} 차원, \n데이터 리스트 \n{1}".format(data.ndim+1, data.reshape(3,2))
print(text)

2 차원, 
데이터 리스트 
[[0 1]
 [2 3]
 [4 5]]


In [31]:
data = numpy.arange(8)
text = "{0} 차원, \n데이터 리스트 \n{1}".format(data.ndim+1, data.reshape(2,2,2))
print(text)

2 차원, 
데이터 리스트 
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [36]:
data = numpy.arange(6)
a = data.reshape(3,2)
print("기본 리스트 데이터\n{0}\n".format(a))

a = a + 10 # a변수에있는 리스트 숫자 전부에 10씩 더한 값출력
print("추가 데이터 리스트\n{0}".format(a))

기본 리스트 데이터
[[0 1]
 [2 3]
 [4 5]]

추가 데이터 리스트
[[10 11]
 [12 13]
 [14 15]]
